backend:
  image:
    repository: tunas106/yas-payment-paypal
    tag: latest
  ingress:
    enabled: true
    host: api-preview.yas.local.com
    path: /payment-paypal
  serviceMonitor:
    enabled: false
