backend:
  image:
    repository: tunas106/yas-recommendation
    tag: staging-latest
  ingress:
    enabled: true
    host: api-preview.yas.local.com
    path: /recommendation
  serviceMonitor:
    enabled: false
