apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/yas-configuration
      helm:
        releaseName: yas-configuration
        valueFiles:
          - $values/argocd/values/staging/yas-configuration.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/backoffice-bff
      helm:
        releaseName: backoffice-bff
        valueFiles:
          - $values/argocd/values/staging/backoffice-bff.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/backoffice-ui
      helm:
        releaseName: backoffice-ui
        valueFiles:
          - $values/argocd/values/staging/backoffice-ui.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/storefront-bff
      helm:
        releaseName: storefront-bff
        valueFiles:
          - $values/argocd/values/staging/storefront-bff.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/storefront-ui
      helm:
        releaseName: storefront-ui
        valueFiles:
          - $values/argocd/values/staging/storefront-ui.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/cart
      helm:
        releaseName: cart
        valueFiles:
          - $values/argocd/values/staging/cart.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/customer
      helm:
        releaseName: customer
        valueFiles:
          - $values/argocd/values/staging/customer.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/inventory
      helm:
        releaseName: inventory
        valueFiles:
          - $values/argocd/values/staging/inventory.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/location
      helm:
        releaseName: location
        valueFiles:
          - $values/argocd/values/staging/location.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/media
      helm:
        releaseName: media
        valueFiles:
          - $values/argocd/values/staging/media.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/order
      helm:
        releaseName: order
        valueFiles:
          - $values/argocd/values/staging/order.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/product
      helm:
        releaseName: product
        valueFiles:
          - $values/argocd/values/staging/product.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/promotion
      helm:
        releaseName: promotion
        valueFiles:
          - $values/argocd/values/staging/promotion.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/rating
      helm:
        releaseName: rating
        valueFiles:
          - $values/argocd/values/staging/rating.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/recommendation
      helm:
        releaseName: recommendation
        valueFiles:
          - $values/argocd/values/staging/recommendation.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/sampledata
      helm:
        releaseName: sampledata
        valueFiles:
          - $values/argocd/values/staging/sampledata.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/webhook
      helm:
        releaseName: webhook
        valueFiles:
          - $values/argocd/values/staging/webhook.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/swagger-ui
      helm:
        releaseName: swagger-ui
        valueFiles:
          - $values/argocd/values/staging/swagger-ui.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
