apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-preview-apps
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/cart
      helm:
        releaseName: cart
        valueFiles:
          - $values/argocd/values/preview/cart.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/order
      helm:
        releaseName: order
        valueFiles:
          - $values/argocd/values/preview/order.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/location
      helm:
        releaseName: location
        valueFiles:
          - $values/argocd/values/preview/location.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/media
      helm:
        releaseName: media
        valueFiles:
          - $values/argocd/values/preview/media.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/promotion
      helm:
        releaseName: promotion
        valueFiles:
          - $values/argocd/values/preview/promotion.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/rating
      helm:
        releaseName: rating
        valueFiles:
          - $values/argocd/values/preview/rating.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/recommendation
      helm:
        releaseName: recommendation
        valueFiles:
          - $values/argocd/values/preview/recommendation.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/sampledata
      helm:
        releaseName: sampledata
        valueFiles:
          - $values/argocd/values/preview/sampledata.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/backoffice-bff
      helm:
        releaseName: backoffice-bff
        valueFiles:
          - $values/argocd/values/preview/backoffice-bff.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/storefront-bff
      helm:
        releaseName: storefront-bff
        valueFiles:
          - $values/argocd/values/preview/storefront-bff.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-preview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
