apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-apps
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/cart
      helm:
        releaseName: cart
        valueFiles:
          - $values/argocd/values/staging/cart.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/order
      helm:
        releaseName: order
        valueFiles:
          - $values/argocd/values/staging/order.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/location
      helm:
        releaseName: location
        valueFiles:
          - $values/argocd/values/staging/location.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/media
      helm:
        releaseName: media
        valueFiles:
          - $values/argocd/values/staging/media.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/promotion
      helm:
        releaseName: promotion
        valueFiles:
          - $values/argocd/values/staging/promotion.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/rating
      helm:
        releaseName: rating
        valueFiles:
          - $values/argocd/values/staging/rating.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/recommendation
      helm:
        releaseName: recommendation
        valueFiles:
          - $values/argocd/values/staging/recommendation.yaml

    - repoURL: https://github.com/TUNAS106/gitops.git
      targetRevision: main
      path: charts/sampledata
      helm:
        releaseName: sampledata
        valueFiles:
          - $values/argocd/values/staging/sampledata.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
